import { PlayerData } from "../types";

export const FRUITS: Record<string, any> = {
  Flame: {
    color: "#ff4500",
    skills: {
      Z: {
        name: "Fire Fist",
        cooldown: 3,
        energy: 10,
        type: "projectile",
        speed: 400,
        size: 20,
        damageMult: 1,
        range: 400,
        color: "#ff4500",
      },
      X: {
        name: "Flame Pillar",
        cooldown: 6,
        energy: 20,
        type: "aoe",
        radius: 100,
        damageMult: 1.5,
        duration: 0.5,
        color: "rgba(255, 69, 0, 0.6)",
      },
      C: {
        name: "Fire Flight",
        cooldown: 8,
        energy: 15,
        type: "dash",
        speed: 800,
        duration: 0.3,
        damageMult: 0.5,
        color: "#ffa500",
      },
    },
  },
  Ice: {
    color: "#00ffff",
    skills: {
      Z: {
        name: "Ice Lance",
        cooldown: 3,
        energy: 10,
        type: "projectile",
        speed: 500,
        size: 15,
        damageMult: 0.8,
        range: 500,
        color: "#00ffff",
      },
      X: {
        name: "Ice Age",
        cooldown: 8,
        energy: 25,
        type: "aoe",
        radius: 120,
        damageMult: 1.2,
        duration: 1,
        freeze: true,
        color: "rgba(0, 255, 255, 0.5)",
      },
      C: {
        name: "Ice Skate",
        cooldown: 5,
        energy: 10,
        type: "dash",
        speed: 700,
        duration: 0.5,
        damageMult: 0,
        color: "#e0ffff",
      },
    },
  },
  Lightning: {
    color: "#ffff00",
    skills: {
      Z: {
        name: "Thunder Strike",
        cooldown: 2,
        energy: 8,
        type: "projectile",
        speed: 800,
        size: 10,
        damageMult: 0.9,
        range: 600,
        color: "#ffff00",
      },
      X: {
        name: "El Thor",
        cooldown: 7,
        energy: 30,
        type: "aoe",
        radius: 80,
        damageMult: 2,
        duration: 0.3,
        color: "rgba(255, 255, 0, 0.8)",
      },
      C: {
        name: "Teleport",
        cooldown: 6,
        energy: 20,
        type: "dash",
        speed: 1500,
        duration: 0.1,
        damageMult: 0,
        color: "#ffffff",
      },
    },
  },
};
